### PR TITLE
improve documentation

### PR DESCRIPTION
**Pull request by SerkanSipahi**
explain where template comes

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by SerkanSipahi** [comment]
CLA, done !

**Comment by ericf** [comment]
@SerkanSipahi thanks for this! Although we plan to remove the docs from the README to keep it developer related and link over to the real docs for this package on the website: http://formatjs.io/handlebars/

**Comment by SerkanSipahi** [comment]
@ericf i know the site.  It is possible to edit it -> http://formatjs.io/handlebars/ ?

**Comment by ericf** [comment]
Yup, the site's code is here: https://github.com/yahoo/formatjs-site

Here's where the docs show the code that "renders" the example templates: https://github.com/yahoo/formatjs-site/blob/master/shared/components/handlebars-example.jsx#L14-18

**Comment by SerkanSipahi** [comment]
@ericf  can you merge the pull request ! i will complete the "improvement of document" on https://github.com/yahoo/formatjs-site

**Comment by SerkanSipahi** [comment]
@ericf  ?

**Comment by ericf** [comment]
@SerkanSipahi like I said, the plan is to gut this README, similar to what we've done here: https://github.com/yahoo/react-intl

**Pull request closed without merging**
